# Generated by Django 2.2.12 on 2020-05-02 14:48

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
            ],
            options={
                'verbose_name': 'Вопросы-ответы',
                'verbose_name_plural': 'Вопросы-ответы',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='quan',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='faq_quan_created_3730e1_brin'),
        ),
    ]
