# Generated by Django 2.2.12 on 2020-04-30 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200414_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
