# Generated by Django 2.2.12 on 2020-05-11 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sity',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='сity',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='UserSkillStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_administrator', models.BooleanField(default=False, verbose_name='Это администратор')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Это модератор')),
                ('is_editor', models.BooleanField(default=False, verbose_name='Это редактор')),
                ('is_advertiser', models.BooleanField(default=False, verbose_name='Это рекламодатель')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Это преподаватель')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_skill_staff', to=settings.AUTH_USER_MODEL, verbose_name='Особый пользователь')),
            ],
            options={
                'verbose_name': 'Особые полномочия в академии',
                'verbose_name_plural': 'Особые полномочия в академии',
            },
        ),
        migrations.CreateModel(
            name='UserAnketaStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_administrator', models.BooleanField(default=False, verbose_name='Это администратор')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Это модератор')),
                ('is_editor', models.BooleanField(default=False, verbose_name='Это редактор')),
                ('is_advertiser', models.BooleanField(default=False, verbose_name='Это рекламодатель')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_anketa_staff', to=settings.AUTH_USER_MODEL, verbose_name='Особый пользователь')),
            ],
            options={
                'verbose_name': 'Особые полномочия в знакомствах',
                'verbose_name_plural': 'Особые полномочия в знакомствах',
            },
        ),
        migrations.CreateModel(
            name='UserAdStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_administrator', models.BooleanField(default=False, verbose_name='Это администратор')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Это модератор')),
                ('is_editor', models.BooleanField(default=False, verbose_name='Это редактор')),
                ('is_advertiser', models.BooleanField(default=False, verbose_name='Это рекламодатель')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_ad_staff', to=settings.AUTH_USER_MODEL, verbose_name='Особый пользователь')),
            ],
            options={
                'verbose_name': 'Особые полномочия в объявлениях',
                'verbose_name_plural': 'Особые полномочия в объявлениях',
            },
        ),
    ]
