# Generated by Django 2.2.12 on 2020-04-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cource',
            options={'ordering': ['-created'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='cource',
            name='video',
            field=models.CharField(default='', max_length=200, verbose_name='Ссылка на вводный видео-ролик'),
            preserve_default=False,
        ),
    ]
