# Generated by Django 2.2.12 on 2020-04-25 20:35

import ad_posts.helpers
from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities', '0002_auto_20200415_1435'),
        ('skill_categories', '0001_initial'),
        ('skill_posts', '0002_auto_20200425_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание курса')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена курса')),
                ('price_acc', models.PositiveIntegerField(default=0, verbose_name='Цена курса со скидкой')),
                ('level', models.CharField(choices=[('Начальный уровень', 'Начальный уровень'), ('Средний уровень', 'Средний уровень'), ('Профессиональный уровень', 'Профессиональный уровень'), ('Все уровни', 'Все уровни')], max_length=50, verbose_name='Цена курса со скидкой')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=ad_posts.helpers.upload_to_user_directory)),
                ('video', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на вводный видео-ролик')),
                ('is_active', models.BooleanField(default=False, verbose_name='Курс активен')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Курс удален')),
                ('is_private', models.BooleanField(default=False, verbose_name='Курс приватный')),
                ('is_free', models.BooleanField(default=False, verbose_name='Курс бесплатный')),
                ('is_one', models.BooleanField(default=False, verbose_name='Индивидуальный курс')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('data_start', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('data_end', models.DateTimeField(blank=True, null=True, verbose_name='Время конца')),
                ('is_reklama', models.BooleanField(default=False, verbose_name='Это реклама')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_categories.SkillSubCategory', verbose_name='Категория')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='Город')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.DeleteModel(
            name='Cource',
        ),
        migrations.AddIndex(
            model_name='course',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='skill_posts_created_c6e21e_brin'),
        ),
    ]
