# Generated by Django 2.2.12 on 2020-04-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_posts', '0004_auto_20200426_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='votes_off',
            field=models.BooleanField(default=False, verbose_name='Лайки-дизлайки отключены'),
        ),
    ]
