# Generated by Django 2.2.12 on 2020-04-30 21:26

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skill_posts', '0005_course_votes_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFavourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_posts.Course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранная анкета',
                'verbose_name_plural': 'Избранные анкеты',
            },
        ),
        migrations.AddIndex(
            model_name='coursefavourites',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='skill_posts_created_a0da83_brin'),
        ),
        migrations.AlterUniqueTogether(
            name='coursefavourites',
            unique_together={('course', 'user')},
        ),
    ]
