# Generated by Django 2.2.12 on 2020-05-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_posts', '0006_auto_20200430_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursefavourites',
            options={'verbose_name': 'Избранный курс', 'verbose_name_plural': 'Избранные курсы'},
        ),
    ]
