# Generated by Django 2.2.12 on 2020-04-30 12:44

import ad_posts.helpers
from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities', '0004_auto_20200427_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('activity', models.TextField(max_length=1000, verbose_name='Деятельность')),
                ('interests', models.TextField(max_length=1000, verbose_name='Интересы')),
                ('favorite_music', models.TextField(max_length=1000, verbose_name='Любимая музыка')),
                ('favorite_films', models.TextField(max_length=1000, verbose_name='Любимые фильмы')),
                ('favorite_books', models.TextField(max_length=1000, verbose_name='Любимые книги')),
                ('about', models.TextField(max_length=1000, verbose_name='О себе')),
                ('political_preferences', models.CharField(choices=[('Не выбраны', 'Не выбраны'), ('Индиффирентные', 'Индиффирентные'), ('Коммунистические', 'Коммунистические'), ('Социалистические', 'Социалистические'), ('Умеренные', 'Умеренные'), ('Либеральные', 'Либеральные'), ('Консервативные', 'Консервативные'), ('Либералистические', 'Либералистические'), ('Ультраконсервативные', 'Ультраконсервативные')], max_length=50, verbose_name='Полит. предпочтения')),
                ('worldview', models.CharField(choices=[('Не выбрано', 'Не выбрано'), ('Иудаизм', 'Иудаизм'), ('Православие', 'Православие'), ('Католицизм', 'Католицизм'), ('Протестантизм', 'Протестантизм'), ('Ислам', 'Ислам'), ('Буддизм', 'Буддизм'), ('Конфуцианство', 'Конфуцианство'), ('Светский гуманизм', 'Светский гуманизм'), ('Пастафарианство', 'Пастафарианство')], max_length=50, verbose_name='Мировоззрение')),
                ('mainthing_in_life', models.CharField(choices=[('Не выбрано', 'Не выбрано'), ('Семья и дети', 'Семья и дети'), ('Карьера и деньги', 'Карьера и деньги'), ('Развлечение и отдых', 'Развлечение и отдых'), ('Наука и исследования', 'Наука и исследования'), ('Совершенствование мира', 'Совершенствование мира'), ('Саморазвитие', 'Саморазвитие'), ('Красота и искусство', 'Красота и искусство'), ('Слава и влияние', 'Слава и влияние')], max_length=50, verbose_name='Главное в жизни')),
                ('mainthing_in_people', models.CharField(choices=[('Не выбрано', 'Не выбрано'), ('Ум и креативность', 'Ум и креативность'), ('Доброта и честность', 'Доброта и честность'), ('Красота и здоровье', 'Красота и здоровье'), ('Власть и богатство', 'Власть и богатство'), ('Смелость и упорство', 'Смелость и упорство'), ('Юмор и жизнелюбие', 'Юмор и жизнелюбие')], max_length=50, verbose_name='Главное в людях')),
                ('attitude_to_smoking', models.CharField(choices=[('Не выбрано', 'Не выбрано'), ('Резко негативное', 'Резко негативное'), ('Негативное', 'ДНегативное'), ('Компромиссное', 'Компромиссное'), ('Помогу бросить курить', 'Помогу бросить курить')], max_length=50, verbose_name='Отношение к курению')),
                ('attitude_to_alcohol', models.CharField(choices=[('Не выбрано', 'Не выбрано'), ('Резко негативное', 'Резко негативное'), ('Негативное', 'ДНегативное'), ('Компромиссное', 'Компромиссное'), ('Помогу бросить пить', 'Помогу бросить пить')], max_length=50, verbose_name='Отношение к алкоголю')),
                ('inspiration', models.CharField(max_length=200, verbose_name='Что меня вдохновляет')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=ad_posts.helpers.upload_to_user_directory)),
                ('is_active', models.BooleanField(default=False, verbose_name='Курс активен')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Курс удален')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('is_reklama', models.BooleanField(default=False, verbose_name='Это реклама')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='Город')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.AddIndex(
            model_name='anketa',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='love_posts__created_66edcf_brin'),
        ),
    ]
