# Generated by Django 2.2.12 on 2020-04-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anketa',
            options={'ordering': ['-created'], 'verbose_name': 'Анкета', 'verbose_name_plural': 'Анкеты'},
        ),
        migrations.AddField(
            model_name='anketa',
            name='votes_off',
            field=models.BooleanField(default=False, verbose_name='Лайки-дизлайки отключены'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Анкета активна'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Анкета удалена'),
        ),
    ]
