# Generated by Django 2.2.12 on 2020-04-30 21:26

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('love_posts', '0002_auto_20200430_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnketaFavourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('anketa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='love_posts.Anketa', verbose_name='Анкета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anketa_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранная анкета',
                'verbose_name_plural': 'Избранные анкеты',
            },
        ),
        migrations.AddIndex(
            model_name='anketafavourites',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='love_posts__created_0189bb_brin'),
        ),
        migrations.AlterUniqueTogether(
            name='anketafavourites',
            unique_together={('anketa', 'user')},
        ),
    ]
