# Generated by Django 2.2.12 on 2020-04-26 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skill_posts', '0004_auto_20200426_1635'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(-1, 'Не нравится'), (1, 'Нравится')], default=0, verbose_name='Голос')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_posts.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
