# Generated by Django 2.2.12 on 2020-04-13 10:41

import ad_posts.helpers
from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание товара')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена товара')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=ad_posts.helpers.upload_to_user_directory)),
                ('is_active', models.BooleanField(default=False, verbose_name='Объявление опубликовано')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Объявление удалено')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Объявление не актуально')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('is_reklama', models.BooleanField(default=False, verbose_name='Это реклама')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_categories.AdSubCategory', verbose_name='Ккатегория')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='Город')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Объявления',
                'verbose_name': 'Объявление',
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=ad_posts.helpers.upload_to_user_directory)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_posts.Ad', verbose_name='Объявление')),
            ],
        ),
        migrations.CreateModel(
            name='AdDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10, verbose_name='Цвет текста')),
                ('background', models.CharField(max_length=10, verbose_name='Цвет фона')),
                ('ad', models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='ad_posts.Ad', verbose_name='Объявление')),
            ],
        ),
        migrations.AddIndex(
            model_name='ad',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='ad_posts_ad_created_6c861e_brin'),
        ),
    ]
