# Generated by Django 2.2.12 on 2020-04-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_posts', '0002_auto_20200415_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
