# Generated by Django 2.2.12 on 2020-04-30 21:26

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad_posts', '0004_ad_votes_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdFavourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_posts.Ad', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное объявление',
                'verbose_name_plural': 'Избранные объявления',
            },
        ),
        migrations.AddIndex(
            model_name='adfavourites',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='ad_posts_ad_created_e28ed1_brin'),
        ),
        migrations.AlterUniqueTogether(
            name='adfavourites',
            unique_together={('ad', 'user')},
        ),
    ]
