# Generated by Django 2.2.12 on 2020-05-10 12:38

import ad_posts.helpers
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ad_posts', '0006_auto_20200502_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='img6',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=ad_posts.helpers.upload_to_user_directory),
        ),
        migrations.AddField(
            model_name='ad',
            name='img7',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=ad_posts.helpers.upload_to_user_directory),
        ),
    ]
