# Generated by Django 2.2.12 on 2020-04-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, unique=True, verbose_name='Латинское название'),
        ),
    ]
