# Generated by Django 2.2.12 on 2020-04-13 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Русское название')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Латинское название')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('image', models.ImageField(blank=True, upload_to='cities', verbose_name='Изображение')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.Region', verbose_name='Регион')),
            ],
            options={
                'verbose_name_plural': 'Города',
                'verbose_name': 'Город',
            },
        ),
    ]
