# Generated by Django 2.2.12 on 2020-04-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Латинское название'),
        ),
    ]
