# Generated by Django 2.2.12 on 2020-04-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_auto_20200427_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['order'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
