# Generated by Django 2.2.12 on 2020-04-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20200427_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['order'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
