# Generated by Django 2.2.12 on 2020-04-26 13:59

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillNumbers',
            new_name='CourseNumbers',
        ),
        migrations.RemoveIndex(
            model_name='coursenumbers',
            name='stst_skilln_created_006f66_brin',
        ),
        migrations.AddIndex(
            model_name='coursenumbers',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='stst_course_created_2f2388_brin'),
        ),
    ]
