# Generated by Django 2.2.12 on 2020-04-30 17:29

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stst', '0003_auto_20200426_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnketaNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(default=0, verbose_name='Кто смотрит')),
                ('anketa', models.PositiveIntegerField(default=0, verbose_name='Какое объявления смотрит')),
                ('platform', models.PositiveIntegerField(default=0, verbose_name='0 Комп, 1 Телефон')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name_plural': 'Просмотры анкеты',
                'verbose_name': 'Просмотр анкеты',
            },
        ),
        migrations.AddIndex(
            model_name='anketanumbers',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='stst_anketa_created_56aa00_brin'),
        ),
    ]
