# Generated by Django 2.2.12 on 2020-04-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcategory',
            name='name_en',
            field=models.CharField(max_length=100, unique=True, verbose_name='Английское название'),
        ),
        migrations.AlterField(
            model_name='adcategory',
            name='name_ru',
            field=models.CharField(max_length=100, unique=True, verbose_name='Русское название'),
        ),
        migrations.AlterField(
            model_name='adsubcategory',
            name='name_en',
            field=models.CharField(max_length=100, unique=True, verbose_name='Английское название'),
        ),
    ]
